"""Add session_token to User model

Revision ID: 9a0f0f32eacb
Revises: e611d8de5ab8
Create Date: 2025-08-03 14:45:08.819673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0f0f32eacb'
down_revision = 'e611d8de5ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Шаг 1: Просто добавляем колонку, без указания unique=True здесь
        batch_op.add_column(sa.Column('session_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_users_session_token', ['session_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # При откате миграции удаляем ограничение по его имени
        batch_op.drop_constraint('uq_users_session_token', type_='unique')
        batch_op.drop_column('session_token')

    # ### end Alembic commands ###
